local gears = require("gears")
local beautiful = require("beautiful")
local dir = gears.filesystem.get_configuration_dir() .. "/icons/flaticons"
local dir2 = gears.filesystem.get_configuration_dir() .. "/icons/layout2/"

local M = {}

--- layouts
M.floating = dir2 .. "floating.png"
M.max = dir2 .. "max.png"
M.tile = dir2 .. "tile.png"
M.dwindle = dir2 .. "dwindle.png"
M.centered = dir2 .. "centered.png"
M.mstab = dir2 .. "mstab.png"
M.equalarea = dir2 .. "equalarea.png"
M.machi = dir2 .. "machi.png"
--tags
M.browser = dir .. "/firefox.svg"
M.code = dir .. "/code-braces.svg"
M.folder = dir .. "/folder.svg"
M.game = dir .. "/google-controller.svg"
M.social = dir .. "/forum.svg"
M.music = dir .. "/music.svg"
M.lab = dir .. "/flask.svg"
--others
M.menu = dir .. "/menu.svg"
M.close = dir .. "/close.svg"
M.closew = dir .. "/closew.svg"
M.logout = dir .. "/logout.svg"
M.sleep = dir .. "/power-sleep.svg"
M.power = dir .. "/power.svg"
M.lock = dir .. "/lock.svg"
M.restart = dir .. "/restart.svg"
M.search = dir .. "/magnify.svg"
M.volume = dir .. "/volume-high.svg"
M.brightness = dir .. "/brightness-7.svg"
M.chart = dir .. "/chart-areaspline.svg"
M.harddisk = dir .. "/harddisk.svg"
M.thermometer = dir .. "/thermometer.svg"
M.plus = dir .. "/plus.svg"
M.color = dir .. "/color.svg"
M.sidebar = dir .. "/sidebar.svg"
M.volumex = dir .. "/volume-x.svg"
M.volume0 = dir .. "/volume.svg"
M.volume1 = dir .. "/volume-1.svg"
M.volume2 = dir .. "/volume-2.svg"
M.terminal = dir .. "/terminal.svg"
M.battery = dir .. "/battery.svg"
M.settings = dir .. "/settings.svg"
M.activity = dir .. "/activity.svg"
M.monitor = dir .. "/monitor.svg"
M.key = dir .. "/key.svg"
M.batt_charging = dir .. "/battery-charge.svg"
M.batt_discharging = dir .. "/battery-discharge.svg"
M.toggled_on = dir .. "/toggled-on.svg"
M.toggled_off = dir .. "/toggled-off.svg"
M.network = dir .. "/network.svg"
M.globe = dir .. "/globe.svg"
M.cpu = dir .. "/cpu.svg"
M.gpu = dir .. "/gpu.svg"
M.arch = dir .. "/arch.svg"
M.maximize = dir .. "/maximize.svg"
M.minus = dir .. "/minus.svg"
M.mic = dir .. "/mic.svg"
M.mic_mute = dir .. "/mic_mute.svg"
M.sun = dir .. "/sun.svg"
M.bluetooth = dir .. "/bluetooth.svg"
M.bluetooth_off = dir .. "/bluetooth-off.svg"
M.loading = dir .. "/loading.svg"
M.airplane_mode = dir .. "/airplane-mode.svg"
M.airplane_mode_off = dir .. "/airplane-mode-off.svg"
M.wifi = dir .. "/wifi.svg"
M.wifi_off = dir .. "/wifi-off.svg"
M.headphone = dir .. "/headphone.svg"
M.next = dir .. "/next.svg"
M.prev = dir .. "/prev.svg"
M.ppause = dir .. "/ppause.svg"
M.left = dir .. "/left.svg"
M.right = dir .. "/right.svg"
M.reading = dir .. "/reading.svg"
M.notepad = dir .. "/notepad.svg"
M.ram = dir .. "/ram.svg"

M.color_icon = function(icon, color)
	local colored_icon = gears.color.recolor_image(icon, color)
	return colored_icon
end

return M
