# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[username]
style_user = "yellow"
style_root = "red"
format = "[$user]($style)"
disabled = false
show_always = true

[directory]
truncation_length = 3
format = "[$path]($style)[$read_only]($read_only_style) "
style = "blue"
read_only = " "
truncation_symbol = "../"
truncate_to_repo = true
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[❯](bold #678979)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[N](bold #5879A6)"
vimcmd_replace_one_symbol = "[R](bold #9C3D55)"
vimcmd_replace_symbol = "[R](bold #9C3D55)"
vimcmd_visual_symbol = "[V](bold #7A5FA6)"

[git_status]
style = "bold #C36316"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
modified = "!${count}"
untracked = "?${count}"
staged = "+${count}"
deleted = "✘${count}"
renamed = "»${count}"
stashed = "\\$${count}"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[cmd_duration]
format = "[$duration]($style)"

[rust]
disabled = true

[package]
disabled = true

[python]
disabled = true

[lua]
disabled = false

[nodejs]
disabled = true
